In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
z = np.array([3, 6, 9, 12, 15])

In [2]:
# covariance
cov_matrix = np.cov([x, y, z])
print("Covariance Matrix:")
print(cov_matrix)

Covariance Matrix:
[[ 2.5  5.   7.5]
 [ 5.  10.  15. ]
 [ 7.5 15.  22.5]]


In [3]:
# correlation coeficient
cor_matrix = np.corrcoef([x, y, z])
print("Correlation Matrix:")
print(cor_matrix)

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
threshold = 0.7

print("Variables with high multicollinearity:")
for i in range(cor_matrix.shape[0]):
    for j in range(i+1, cor_matrix.shape[1]):
        if abs(cor_matrix[i, j]) > threshold:
            print(f"Variable {i+1} and Variable {j+1}")

Variables with high multicollinearity:
Variable 1 and Variable 2
Variable 1 and Variable 3
Variable 2 and Variable 3
