# 텐서 기본 실습

In [1]:
import torch
import numpy as np
import torchvision

## 텐서 초기화하기 데이터로부터 직접 텐서를 생성 가능합니다.

In [2]:
# 1. torch 이용해서 만든 텐서
data = [[1,2], [3,4]]
print(type(data))
x_data = torch.tensor(data)

print(x_data)

# 2. Numpy 이용해서 만든 텐서
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

<class 'list'>
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


torch.tensor()는 입력 텐서를 복사하여 새로운 텐서를 만듭니다. 이 함수는 항상 새로운 메모리를 할당하므로, 원본 데이터와의 메모리 공유가 이루어지지 않습니다.

torch.from_numpy() 함수는 NumPy 배열을 PyTorch 텐서로 변환할 때, 원본 데이터와의 메모리 공유를 유지합니다.

In [3]:
x_ones = torch.ones_like(x_data)
print(f"ones Tensor : \n{x_ones}")
# torch.ones_like() : 주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든 요소를 1로 채움.

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data 속성을 덮어씁니다.
print(f'Random Tensor : \n{x_rand}')

# torch.rand_like() : 주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든 요소를 랜덤한 값으로 채웁니다.
# 그리고 타입 지정하면 그 타입으로 변경됩니다.
# 0 ~ 1 사이의 랜덤한 값으로 초기화되고 데이터 타입유형은 dtype=torch.float으로 지정.

ones Tensor : 
tensor([[1, 1],
        [1, 1]])
Random Tensor : 
tensor([[0.3863, 0.1398],
        [0.9139, 0.5497]])


In [4]:
# 무작위 또는 상수 값을 사용하기
shape = (5,6,)
rand_tensor = torch.rand(shape) * 10 # 0 ~ 10
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("rand_tensor \n", rand_tensor)
print("ones_tensor \n", ones_tensor)
print("zeros_tensor \n", zeros_tensor)

# 유효 범위를 최소값 얼마부터 ~ 최대값 얼마까지 6 ~ 10
shape_temp = (5,6,)
min_val = 6
max_val = 10
rand_tensor_temp = torch.rand(shape_temp) * (max_val - min_val) + min_val
print(rand_tensor_temp)

rand_tensor 
 tensor([[2.8247, 6.8903, 9.1454, 7.8544, 6.3501, 9.9675],
        [5.1391, 9.7678, 3.6735, 8.7253, 9.6519, 8.1993],
        [6.3895, 0.7208, 9.3107, 0.7978, 8.0520, 3.6414],
        [9.8785, 3.8914, 8.3690, 3.9592, 2.4874, 4.5899],
        [8.1779, 3.2191, 6.1233, 7.5001, 7.7444, 2.0856]])
ones_tensor 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
zeros_tensor 
 tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[9.8089, 9.7246, 7.0811, 6.5329, 7.8523, 8.0980],
        [6.0733, 6.6943, 7.5571, 7.8540, 6.7829, 7.7042],
        [8.1803, 7.3492, 7.9024, 6.3430, 8.1627, 7.3356],
        [9.5202, 6.1997, 9.3043, 7.1709, 8.2970, 6.2990],
        [8.7034, 9.5886, 8.7476, 7.0300, 8.1019, 8.2140]])


## 텐서 속성

In [5]:
tensor_val = torch.rand(3,4)
print(tensor_val)

# 디바이스 정보 가져오기 - 그냥 암기
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

# tensor_val.to("cuda") >> cuda로 변경

# 디바이스 변경하고자 하는경우
# 텐서의 디바이스를 변경하려면 to() 메서드를 사용할 수 있습니다. 이 메서드는 새로운 디바이스로 텐서를 이동시킵니다.
# EX) model.to(device)

print(f"Shape of tensor : {tensor_val.shape}")
print(f"Data type of tensor : {tensor_val.dtype}")
print(f"Device tensor is stored on : {tensor_val.device}")

tensor([[0.0804, 0.4288, 0.7107, 0.4687],
        [0.5579, 0.3218, 0.7743, 0.3634],
        [0.0176, 0.7271, 0.7097, 0.0095]])
cpu
Shape of tensor : torch.Size([3, 4])
Data type of tensor : torch.float32
Device tensor is stored on : cpu


In [6]:
# 표준 인덱싱과 슬라이싱
tensor_1 = torch.ones(4,4)
tensor_1[:,3] = 0
print(tensor_1)

tensor_2 = torch.ones(4,4)
tensor_2[:,1] = 2
print(tensor_2)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])


In [7]:
# 텐서 합치기
t1 = torch.cat([tensor_1, tensor_1, tensor_1], dim=1)
print(t1)

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])


In [8]:
t_mult = tensor_1.mul(tensor_2)
print(t_mult)

print(tensor_1 * tensor_2)

tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])
tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])


In [9]:
# 행렬 곱
print(tensor_2.matmul(tensor_2.T))
print(tensor_2 @ tensor_2.T)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [10]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경

In [11]:
"""
파이토치 텐서의 뷰는 넘파이의 Reshape와 같은 역할
Reshape > 텐서의 크기를 변경해주는 역할
"""

# 3차원 데이터 생성
t_temp = np.array([[[0,1,2], [3,4,5], [6,7,8], [9,10,11]]])
ft = torch.FloatTensor(t_temp)
print(ft)
print(ft.shape)

# 이제 ft view -> 2차원 텐서로 변경
# -1 : 나는 그 값을 모르겠으니 파이토치 니가 알아서 해 ! : 두번째 차원은 길이는 3 가지도록 하라는 의미.
print(ft.view([-1,3])) # (?, 3)
print(ft.view([-1,3]).shape)

# view() 메서드를 사용하여 텐서의 차원을 변경하면, -> 데이터를 복사하여 새로운 텐서를 생성하고 이 새로운 텐서는 원래 텐서와 메모리를 공유안함!

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([1, 4, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [12]:
# 3차원 텐서의 크기 변경
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [13]:
"""
스퀴즈 -> 1차원을 제거
스퀴즈는 차원이 1인 경우에는 해당 차원을 제거합니다.
실습 3x1 크기를 가지는 2차원 텐서 생성
"""

ft = torch.FloatTensor(([0],[1],[2]))
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [14]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [15]:
"""
언스퀴즈 - 특정 위치에서 1인 차원을 추가합니다.
"""
ft_temp = torch.Tensor([0,1,2])
print(ft_temp.shape)

torch.Size([3])


In [16]:
# 첫번째 차원에서 1차원 추가
# 인덱스 0
print(ft_temp.unsqueeze(0))
print(ft_temp.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [17]:
print(ft_temp.view(1, -1))
print(ft_temp.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [18]:
# 두번째 차원에 1추가
print(ft_temp.unsqueeze(1))
print(ft_temp.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [19]:
print(ft_temp.unsqueeze(-1))
print(ft_temp.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
