## 단일 객체 저장 및 불러오기

In [2]:
import numpy as np
import os

In [3]:
# 단일 객체 생성
array = np.arange(1, 10)
print(array)

[1 2 3 4 5 6 7 8 9]


#### numpy 형태로 저장

In [4]:
os.makedirs("./data", exist_ok=True)
np.save("./data/save.npy", array)

#### numpy 데이터 불러오기

In [5]:
result = np.load("./data/save.npy")

print(result)

[1 2 3 4 5 6 7 8 9]


# 복수 객체 저장 및 불러오기

In [7]:
# 복수 객체 생성 
array01 = np.arange(0,10)
array02 = np.arange(10,20)
array03 = np.arange(20,30)

#### numpy 저장

In [8]:
np.savez("./data/mul_save.npz", a=array01, array2=array02, array3=array03)
# 여러개일 땐 savez

#### numpy 불러오기 

In [10]:
data = np.load("./data/mul_save.npz")

result01 = data['a']
result02 = data['array2']
print(result01)
print(result02)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
