# numpy를 사용하여 이미지 저장 시 효율 비교

In [1]:
#!pip install Pillow

In [2]:
import numpy as np
from PIL import Image

In [3]:
# 이미지 불러오기
img = Image.open("./data/cat.png").convert('L') # 그레이 스케일 변환
print(img)

<PIL.Image.Image image mode=L size=310x162 at 0x20A6D43A830>


In [4]:
img_array = np.array(img)
print(img_array)

[[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]


In [5]:
np.save("./data/pil_image.npy", img_array)

In [6]:
img_array1 = np.load("./data/pil_image.npy")

print(img_array1)

[[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]


In [7]:
# 다시 PIL 이미지로 변환 
img = Image.fromarray(np.uint8(img_array1))
img.save("./data/image_numpy.png")

In [8]:
import os 
np_save_size = os.path.getsize("./data/pil_image.npy")

pil_save_size = os.path.getsize("./data/image_numpy.png")
print(f'numpy.save() 함수로 저장한 파일 크기: {np_save_size} bytes')
print(f'PIL.Image.fromarray() 함수로 저장한 파일 크기: {pil_save_size} bytes')

numpy.save() 함수로 저장한 파일 크기: 50348 bytes
PIL.Image.fromarray() 함수로 저장한 파일 크기: 26808 bytes
